version: v1

# initial size for new user
init_user_storage_size: 2147483648 # aka, 2GiB

# auth_secret_key
auth_secret_key: amisecret?

# salt val for password cryption
pw_salt: "*12#3"

# tls
tls:
  key: /tls/www.easydisk.top.key
  crt: /tls/www.easydisk.top_bundle.crt

mysql:
  user: "chang"
  password: "mysql123456"
  # addr: "mysql:3306"
  addr: "localhost:3306"
  db_name: "netdisk"

mongo:
  # addr: "mongodb://mongodb:27017"
  addr: "mongodb://localhost:27017"
  db_name: "netdisk"

redis:
  # addr: "redis:6379"
  addr: "localhost:6379"
  db_share: 0
  db_upload: 1
  user:
  password: